version: '3.8'

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_URL=redis://redis:6379/0
      - PORT=8000
      - PYTHONPATH=/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload --reload-dir /app
    depends_on:
      - redis

  worker:
    build: .
    volumes:
      - ./api:/app
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_URL=redis://redis:6379/0
      - PYTHONPATH=/app
    command: celery -A celery_app.celery_app worker -l info
    depends_on:
      - redis 