version: '3.8'

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  web:
    build: .
    ports:
      - "8001:8000"
    volumes:
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_URL=redis://redis:6379/0
      - PORT=8000
      - PYTHONPATH=/app
    command: ["./entrypoint.sh", "web"]
    depends_on:
      - redis

  worker:
    build: .
    volumes:
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_URL=redis://redis:6379/0
      - PYTHONPATH=/app
    command: ["./entrypoint.sh", "worker"]
    depends_on:
      - redis