name: Deploy to Cloud Run

on:
  push:
    branches:
      - production

env:
  GOOGLE_PROJECT_ID: ${{ secrets.GOOGLE_PROJECT_ID }}
  GCP_REGION: asia-northeast3 # Cloud Run 서비스가 배포된 리전
  CLOUD_RUN_SERVICE_NAME: cvfactory-server # Cloud Run 서비스 이름
  ARTIFACT_REGISTRY_REPOSITORY: cloud-run-source-deploy # Artifact Registry 저장소 이름

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ${{ secrets.WIP_PROVIDER }} # 워크로드 ID 연동 제공자
          service_account: github-actions-deployer@${{ secrets.GOOGLE_PROJECT_ID }}.iam.gserviceaccount.com # 생성한 서비스 계정 이메일

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Get short commit SHA
        id: vars
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Authorize Docker to push to Artifact Registry
        run: gcloud auth configure-docker ${{ env.GCP_REGION }}-docker.pkg.dev --quiet

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GOOGLE_PROJECT_ID }}/${{ env.ARTIFACT_REGISTRY_REPOSITORY }}/${{ env.CLOUD_RUN_SERVICE_NAME }}:${{ env.SHORT_SHA }}
            ${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GOOGLE_PROJECT_ID }}/${{ env.ARTIFACT_REGISTRY_REPOSITORY }}/${{ env.CLOUD_RUN_SERVICE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy to Cloud Run
        run: |-
          gcloud run deploy ${{ env.CLOUD_RUN_SERVICE_NAME }} \
            --image "${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GOOGLE_PROJECT_ID }}/${{ env.ARTIFACT_REGISTRY_REPOSITORY }}/${{ env.CLOUD_RUN_SERVICE_NAME }}:${{ env.SHORT_SHA }}" \
            --region "${{ env.GCP_REGION }}" \
            --platform "managed" \
            --port "8080" \
            --allow-unauthenticated \
            --quiet # 필요에 따라 인증 설정 변경 